### ISSUE TITLE
Errno::EPERM: Operation not permitted @ dir_s_mkdir - /usr/local/opt/cython/libexec/lib/python3.11

### ISSUE THREAD

**Issue by fschoell** [mulbc/homebrew-ceph-client#33]
Seems like Cython updated it's Python dependency to 3.12, so this is likely just the same issue as in #24 with Python 3.12 as new requirement?

Output: 

```
➜  ~ brew install ceph-client

==> Fetching mulbc/ceph-client/ceph-client
==> Downloading https://files.pythonhosted.org/packages/cb/7d/7e6bc4bd4abc49e9f4f5c4773bb43d1615e4b476d108d1b527318b9c6521/prettytable-3.2.0.tar.gz
Already downloaded: /Users/fred/Library/Caches/Homebrew/downloads/4c52d4026151aa261d150292e430951006c98d7d72a89034ecea460b2f2c111b--prettytable-3.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz
Already downloaded: /Users/fred/Library/Caches/Homebrew/downloads/83f6bef3a0a4fd3d9559a85acb4ab73b0e4544f8542e67bf54929e86653356e9--PyYAML-6.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/89/38/459b727c381504f361832b9e5ace19966de1a235d73cdbdea91c771a1155/wcwidth-0.2.5.tar.gz
Already downloaded: /Users/fred/Library/Caches/Homebrew/downloads/bc4d16c76a1cb1eecc9775864d059d1cfb00289c163bc86440fcd6eef95aa2d8--wcwidth-0.2.5.tar.gz
==> Downloading https://download.ceph.com/tarballs/ceph-17.2.5.tar.gz
Already downloaded: /Users/fred/Library/Caches/Homebrew/downloads/b368830312f6eb917b2570de1804003eb370a49ca1887c698544c64b8c8c8313--ceph-17.2.5.tar.gz
==> Installing ceph-client from mulbc/ceph-client
==> Patching
Error: An exception occurred within a child process:
  Errno::EPERM: Operation not permitted @ dir_s_mkdir - /usr/local/opt/cython/libexec/lib/python3.11
```

```
➜  ~ ls /usr/local/opt/cython/libexec/lib
python3.12
```

**Comment by fschoell** [comment]
Updated Python to 3.12, but I'm getting this issue (tried updating PyYAML to 6.0.1 as well), has anybody an idea what causes this:

```
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/ceph-client/17.2.7_1/libexec/vendor --install-scripts=/usr/local/Cellar/ceph-client/17.2.7_1/libexec/vendor/bin --install-lib=/usr/local/Cellar/ceph-client/17.2.7_1/libexec/vendor/lib/python3.12/site-packages --single-version-externally-managed --record=installed.txt
running install
/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running build
running build_py
creating build
creating build/lib.macosx-14.0-x86_64-cpython-312
creating build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/scanner.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/error.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/constructor.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/composer.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/events.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/__init__.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/representer.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/tokens.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/dumper.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/cyaml.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/parser.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/reader.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/loader.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/resolver.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/serializer.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/nodes.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
copying lib/yaml/emitter.py -> build/lib.macosx-14.0-x86_64-cpython-312/yaml
creating build/lib.macosx-14.0-x86_64-cpython-312/_yaml
copying lib/_yaml/__init__.py -> build/lib.macosx-14.0-x86_64-cpython-312/_yaml
warning: build_py: byte-compiling is disabled, skipping.

running build_ext
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "setup.py", line 289, in <module>
    setup(
  File "/usr/local/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.12/site-packages/setuptools/command/install.py", line 81, in run
    return orig.install.run(self)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/install.py", line 697, in run
    self.run_command('build')
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 191, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "setup.py", line 233, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: cython_sources
```

**Comment by tabakovsasha** [comment]
> Updated Python to 3.12

Hello @fschoell I'm faced with the same issue today. Could you please tell me how did you solve it?
Just updated ceph-client.rb and run lovally?

**Comment by nioshield** [comment]
@fschoell  I have the same problem,  Could you please tell me how did you solve it?

**Comment by fschoell** [comment]
Unfortunately I won't be able to help you. Tried updating some dependencies but that just created new issues. I moved to a Linux VM as I just needed this client for some testing.
